# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-prompt", "~> 0.21.0"

gem "tty-table", "~> 0.11.0"

gem "tty-font", "~> 0.5.0"

gem "colorize", "~> 0.8.1"

gem "pp", "~> 0.1.1"

gem "mac-say", "~> 0.2.1"

gem "json", "~> 2.3"

gem "singleton", "~> 0.1.0"

gem "rest-client", "~> 2.1"
